version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    volumes:
      - .:/usr/src/app
      - "/usr/src/app/node_modules"
    command: ["npm", "start"]
    networks:
     - map-network

networks:
  map-network: