FROM node:18-alpine

WORKDIR /usr/src/app
# add `/app/node_modules/.bin` to $PATH
# ENV PATH  /usr/src/app/node_modules/.bin:$PATH
RUN npm cache clean --force
RUN npm install -g create-react-app
COPY package.json ./
RUN npm install react-scripts --global
RUN npm install --force
COPY . . 

EXPOSE 3000

CMD [ "npm","start" ]